### ISSUE TITLE
text_input width doesn't alter the actual width

### ISSUE THREAD

**Issue by fantypants** [boydm/scenic#105] opened 2018-11-09 01:15 UTC
### Checklist

- [x] Check other issues and make sure that it is not reported yet.

### Versions and Environment

Elixir: 1.7
Erlang: 21

Scenic: 
```
    scenic 0.9.0 (Hex package) (mix)
    locked at 0.9.0 (scenic) 129594f9
    scenic_driver_glfw 0.9.0 (Hex package) (mix)
    locked at 0.9.0 (scenic_driver_glfw) 4c7a8300
```

OS: Ubuntu 16.04

### Steps to reproduce

```text_field("", id: :text, width: 40, hint: "Type here...", t: {200, 160})```

### Expected Behavior

Width of the component to be 40 

### Actual Behavior
Defaults to 240

Struct From Inspection:
```%Scenic.Primitive{
  data: {Scenic.Component.Input.TextField, ""},
  id: :key_input,
  module: Scenic.Primitive.SceneRef,
  parent_uid: 1,
  styles: %{
    fontsize: 15,
    height: 20,
    hint: "Paste Private Key or Pneumonic",
    t: {100, 200},
    w: 1000
  },
  transforms: %{translate: {100, 200}}
}
```
</details>

### Additional Comments
Any Width inputted doesn't change the width, I've used ```:w and :width as per the docs```

**Comment by yordis** [comment] 2018-11-09 01:19
@fantypants `Scenic:  Latest` what do you mean by `Latest`?

 Do you mean `Latest version on Hex` or `Latest version from Github`, or `Latest version of a fork`? 🤷‍♂️ 

I will suggest to use `mix deps | grep scenic` and copy the version that appears, or open `mix.lock` and copy the version that appears for `scenic`.

**Comment by fantypants** [comment] 2018-11-09 05:19
> mix deps | grep scenic

* scenic 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (scenic) 129594f9
* scenic_driver_glfw 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (scenic_driver_glfw) 4c7a8300

**Comment by fantypants** [comment] 2018-11-12 02:14
Fixed the problem, opened a PR Request and awaiting approval

**Comment by boydm** [comment] 2018-11-13 00:11
PR is merged and I added a test for it.
Closing issue.

Thank you for finding and fixing it!

**Closed by boydm** 2018-11-13 00:11 UTC

**Comment by fantypants** [comment] 2018-11-13 03:20
No worries :) thank you for the quick turnaround

**Comment by sb3rg** [comment] 2019-03-11 05:01
## Versions and Environment
Elixir: 1.7.4
Erlang: 21
Scenic: 0.9
OS: Arch Linux

## Steps to Reproduce
`text_field("", id: :text, width: 5, hint: "> ", t: {20, 30})`

## Behavior
Used 5 as width to showcase how absurdly off the width is.  Won't work for large values of `:w`/`:width`, either, though.
![screenshot](https://user-images.githubusercontent.com/4951467/54100774-37accf80-438e-11e9-89e7-0a9dd908b844.png)

## Comments
Would prefer to have the box not only width adjustable by height adjustable, too, to make it REPL-esque.  For now I would settle for just being able to have any control over the width of the box, though.  Any idea what's going on?  Looks like this issue has been closed.

**Comment by boydm** [comment] 2019-03-11 10:29
many of the components are being change to be more dynamic in sizing. Much of that work has been blocked on the font metrics, which is now in the "fm" branch. I haven't gotten to the text control yet, bu t will soon. I'll keep all this in mind when I crack code open again.

**Comment by sb3rg** [comment] 2019-03-15 06:10
Thank you! Love playing with Scenic so far.  It's been very easy to use and it just works.  Can't wait to see what people build with this.
